import React, { useState, useEffect} from 'react'
import { Loader, Card, FormField } from "../Components";

// Create the ReanderCards Componnent

const RenderCards = (props) => {
  const { data, title } = props;
  if (data?.length > 0) {
    return data.map((post) =>
      <Card key= {post._id} {...post} />
    )
  }
else {
    return (
      <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
    )
  }
}

const Home = () => {
  // Declare the useState Hook initially
  const [Loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setsearchText] = useState("");
  const [SearchResults, setSearchResults] = useState(null);
  const [searchTimeOut, setSearchTimeOut] = useState(null)

  // Using useEffect hooks to fetch the All Posts
  useEffect(() => {
    const fetchPosts = async () =>{
      setLoading(true);
      try {
        const response = await fetch('http://localhost:8080/api/v1/post',{
          method : 'GET',
          headers:{
            "Content-Type" : "application/json"
          },
        })
        if(response.ok){
          const result = await response.json()
          setAllPosts(result.data.reverse())
          // console.log(allPosts);
        }
      } catch (error) {
        alert(error)
      }
      finally{
        setLoading(false)
      }
    }
    fetchPosts()
  }, [])

  // Handle the search 
  const handleSearchChange = (e)=>{
    setsearchText(e.target.value);
    setSearchTimeOut(setTimeout(()=>{
      const searchResults = allPosts.filter((item)=> item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()));
      setSearchResults(searchResults)
    },500))
    
  }
  return (
    <>
      <section className='max-w-7 mx-auto'>
        <div>
          <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>
          <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>Browse through a collection of imagination and visually stunnig images generated by DALL-E-AI</p>
        </div>
        <div className="mt-16">
          <FormField
          labelName = "Search Posts"
          type = 'text'
          name = "text"
          placeholder = "Search posts"
          value = {searchText}
          handleChange = {handleSearchChange}
          display = 'hidden'
           />
        </div>

        <div className="mt-10">
          {Loading ? (
            <div className="flex justify-center items-center">
              <Loader />
            </div>
          ) : (
            <div>
              {searchText && (
                <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                  Showing results for <span className='text-[#222328]'>{searchText}</span>
                </h2>
              )}
              <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-col-2 grid-col-1 gap-3">
                {searchText ? (
                  <RenderCards
                    data={SearchResults}
                    title="No search results found"
                  />
                ) : (
                  <RenderCards
                    data={allPosts}
                    title="No posts found"
                  />
                )}
              </div>
            </div>
          )}
        </div>
      </section>
    </>
  )
}

export default Home